version: "3.4"

services:

  database:
    image: mysql:5.7-debian
    container_name: mysql-db
    hostname: database
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=book_store_db
      -
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  book-store-app:
    image: book-store-app:0.0.1
    container_name: book-store-app
    environment:
      DATABASE_HOSTNAME: database
    restart: on-failure
    ports:
      - 8002:8002
    depends_on:
      - database

volumes:
  mysql-data: