version: "3.4"

services:

  database:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=book_store_db

  book-store-app:
    image: book-store-app:0.0.1
    container_name: book-store-app
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  mysql-data: