version: "3.4"

services:

  database:
    image: mysql:5.7-debian
    container_name: mysql-db
    hostname: database
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=book_store_db

  book-store-app:
    image: book-store-app:0.0.1
    container_name: book-store-app
    environment:
      DATABASE_HOSTNAME: database
    restart: on-failure
    ports:
      - 8002:8002
    depends_on:
      - database

volumes:
  mysql-data: