spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: book-events-group
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 1
        retries: 3
        retry.backoff.ms: 1000
        max.block.ms: 20000
        delivery.timeout.ms: 30000
    admin:
      properties:
        bootstrap.servers: localhost:29092

topics:
  book:
    events: book-events-topic