spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: book-events-group
    producer:
      bootstrap-servers: localhost:9092
      properties:
        acks: 1
        retries: 3
        retry.backoff.ms: 1000
        max.block.ms: 20000
        delivery.timeout.ms: 30000
    admin:
      properties:
        bootstrap.servers: localhost:9092

topics:
  book:
    events: book-events-topic
    dead-letter: book-events-DLT-topic