apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  labels:
    app: mysql-db-service
spec:
  selector:
    app: book-store-db
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP