apiVersion: v1
kind: Service
metadata:
  name: book-store-app-service
  namespace: book-store-dev
spec:
  selector:
    app: book-store-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP